title = "Ramana Venkata"
theme = "hugo-theme-yinyang"
baseURL = "https://vramana.github.io/blog"
languageCode = "en-us"

[author]
  name = "Ramana Venkata"
  homepage = "https://vramana.github.io/blog"

publishDir = "docs"

[languages]
  [languages.en]
    contentDir = "content"
    languageName = "English"
    weight = 1

[[params.socials]]
name = "About Me"
link = "/blog/about"

[[params.socials]]
name = "Github"
link = "https://github.com/vramana"


[[params.socials]]
name = "Twitter"
link = "https://twitter.com/_vramana"
