title = "Ramana Venkata"
baseURL = "https://blog.vramana.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
publishDir = "docs"
enableEmoji = true
pygmentsCodefences = true
pygmentsUseClasses = true

theme = "hyde"

[author]
name = "Ramana Venkata"
homepage = "https://blog.vramana.com"

[params]
description = "Senior Software Engineer with interest Javascript, TypeScript and Rust"
themeColor = "theme-base-0d"

[[params.socials]]
name = "Github"
link = "https://github.com/vramana"


[[params.socials]]
name = "Twitter"
link = "https://twitter.com/_vramana"

