title = "Ramana Venkata"
baseURL = "https://blog.vramana.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
publishDir = "docs"
enableEmoji = true

theme = "hyde"

[[params.author]]
name = "Ramana Venkata"
homepage = "https://blog.vramana.com"

[params]
description = "Senior Software Engineer with an interest in Javascript, TypeScript and Rust"

[[params.socials]]
name = "Github"
link = "https://github.com/vramana"


[[params.socials]]
name = "Twitter"
link = "https://twitter.com/_vramana"


[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/vramana"},
      {Name = "Mastodon", URL = "https://mastodon.social/@vramana"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/vramanamath/"},
  ]

[markup]
[markup.highlight]
style = "github-dark"
